apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: my-project
  name: deployment-example
spec:
  replicas: 2
  selector:
    matchLabels:
      app: project
  template:
    metadata:
      labels:
        app: project

    spec:
      containers:                      # Correctly indented under template.spec
        - name: deployment
          image: dsnkumar121/project:latest
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: database-1.cpa8i48eqilt.ap-south-1.rds.amazonaws.com
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: stu_projects
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: postgres
